//! Public facade for the `RSpin` library workspace.

pub use rspin_analysis as analysis;
pub use rspin_core as core;
pub use rspin_io as io;
pub use rspin_prediction as prediction;
pub use rspin_processing as processing;
pub use rspin_simulation as simulation;

mod workflow;

pub use analysis::{
    AlignmentWindow, AnalyzeSpectrum1D, AnalyzeSpectrum1DResult, AnalyzeSpectrum2D,
    AnalyzeSpectrum2DResult, AssignedAtom, Assignment, AssignmentSet, AssignmentTarget,
    BilinearIntegrator2D, BucketMatrix1D, BucketMatrix2D, BucketOptions1D, BucketOptions2D,
    ClusterMerge, ConsensusPeak1D, ConsensusPeakMember1D, ConsensusPeakOptions, ConsensusRange1D,
    ConsensusRangeMember1D, ConsensusRangeOptions, ConsensusZone2D, ConsensusZoneMember2D,
    ConsensusZoneOptions, CouplingNode, DetectedMultiplet, DetectedRange, DetectedZone,
    GapMultipletDetector, Integral, Integral2D, IntegralRegion, IntegralRegion2D, Integrator,
    Integrator2D, JCoupling, JCouplingGraph, LocalExtremaPeakPicker, MatrixClusterCut,
    MatrixClusterMetric, MatrixClusterResult, MatrixClusteringOptions, MatrixGeneration2DOptions,
    MatrixGenerationOptions, MatrixLinkage, MatrixPairwiseMetric, MatrixPairwiseOptions,
    MatrixPairwiseResult, MatrixPcaOptions, MatrixPcaResult, MatrixScaling,
    MultipletDetectionOptions, MultipletDetector, MultipletKind, OptimizedPeak, Peak,
    PeakAlignedMatrix1D, PeakAlignmentOptions, PeakAlignmentResult1D, PeakOptimizationOptions,
    PeakOptimizer, PeakPickOptions, PeakPicker, PeakPolarity, QuadraticPeakOptimizer,
    RangeDetectionOptions, RangeDetector, SignalSummary1D, SignalSummary2D, SignalSummary2DOptions,
    SignalSummaryOptions, SpectralBucket1D, SpectralBucket2D, Spectrum2DAlignmentShift,
    SpectrumAlignmentShift, SpectrumAnalysis1D, SpectrumAnalysis1DOptions,
    SpectrumAnalysis1DResultWorkflow, SpectrumAnalysis1DWorkflow, SpectrumAnalysis2D,
    SpectrumAnalysis2DOptions, SpectrumAnalysis2DResultWorkflow, SpectrumAnalysis2DWorkflow,
    SpectrumMatrix1D, SpectrumMatrix2D, ThresholdRangeDetector, ThresholdZoneDetector,
    TrapezoidalIntegrator, ZoneAlignedMatrix2D, ZoneAlignmentOptions, ZoneAlignmentResult2D,
    ZoneConnectivity, ZoneDetectionOptions, ZoneDetector, align_spectra_by_peak,
    align_spectra_by_peak_to_matrix, align_spectra_by_zone, align_spectra_by_zone_to_matrix,
    analyze_assigned_spectrum_1d, analyze_assigned_spectrum_2d, analyze_spectrum_1d,
    analyze_spectrum_2d, bucket_spectra_1d, bucket_spectra_2d, bucket_spectrum_1d,
    bucket_spectrum_2d, cluster_bucket_matrix_1d, cluster_bucket_matrix_2d, cluster_matrix,
    cluster_spectrum_matrix_1d, cluster_spectrum_matrix_2d, detect_consensus_peaks_1d,
    detect_consensus_ranges_1d, detect_consensus_zones_2d, detect_multiplets, detect_ranges,
    detect_zones, deterministic_assignment_id, deterministic_j_coupling_id,
    generate_spectrum_matrix_1d, generate_spectrum_matrix_2d, integrate_ranges, integrate_region,
    integrate_region_2d, integrate_regions, integrate_regions_2d, integrate_zones_2d,
    optimize_peaks_quadratic, pairwise_bucket_matrix_1d, pairwise_bucket_matrix_2d,
    pairwise_matrix, pairwise_spectrum_matrix_1d, pairwise_spectrum_matrix_2d,
    pca_bucket_matrix_1d, pca_bucket_matrix_2d, pca_matrix, pca_spectrum_matrix_1d,
    pca_spectrum_matrix_2d, pick_peaks, summarize_signals_1d, summarize_signals_2d,
};
pub use core::{
    AnnotationTarget, Atom, Axis, Bond, BondOrder, Metadata, Molecule, Nucleus, ProcessingRecord,
    RSpinError, Result, Spectrum1D, Spectrum2D, SpectrumAnnotation, Unit, atoms_from_formula,
};
pub use io::{
    ANALYSIS_1D_JSON_FORMAT, ANALYSIS_2D_JSON_FORMAT, ANALYSIS_JSON_VERSION,
    ASSIGNMENT_JSON_VERSION, ASSIGNMENT_SET_JSON_FORMAT, AgilentFid1D, AgilentFid2D,
    AgilentProcessed1D, AgilentProcessed2D, AutoSpectrum1DPath, AutoSpectrum1DPathWriter,
    AutoSpectrum1DText, AutoSpectrum2DPath, AutoSpectrum2DPathWriter, AutoSpectrum2DText,
    BrukerFid1D, BrukerProcessed1D, BrukerProcessed2D, BrukerSer2D, CsvAnalysis1D, CsvAnalysis2D,
    CsvExactTransitions, CsvPrediction, CsvSpectrum1D, CsvSpectrum2D,
    EXACT_DECOMPOSITION_1D_JSON_FORMAT, EXACT_DECOMPOSITION_2D_JSON_FORMAT,
    EXACT_SPECTRUM_1D_OPTIONS_JSON_FORMAT, EXACT_SPECTRUM_2D_OPTIONS_JSON_FORMAT,
    EXACT_SPIN_OPTIONS_JSON_FORMAT, EXACT_TRANSITIONS_JSON_FORMAT, J_COUPLING_GRAPH_JSON_FORMAT,
    JcampDx, JeolJdf1D, JeolJdf2D, JsonAnalysis1D, JsonAnalysis2D, JsonAssignmentSet,
    JsonExactDecomposition1D, JsonExactDecomposition2D, JsonExactSpectrum2DOptions,
    JsonExactSpectrumOptions, JsonExactSpinOptions, JsonExactTransitions, JsonJCouplingGraph,
    JsonNmreDataRecord, JsonNmreDataRecords, JsonPrediction, JsonProcessingRecipe1D,
    JsonProcessingRecipe2D, JsonSpectrum1D, JsonSpectrum2D, JsonSpinHalfSystem,
    NMREDATA_JSON_VERSION, NMREDATA_RECORD_JSON_FORMAT, NMREDATA_RECORDS_JSON_FORMAT,
    NMRML_SCHEMA_DIRECTORY, NMRML_SCHEMA_REPOSITORY, NmrMl1D, NmrMl2D, NmrMlDocumentInfo,
    NmrMlSchemaLocation, NmrMlVersion, NmreData, NmreDataAnalysis, NmreDataAssignment,
    NmreDataCoupling, NmreDataRecord, NmreDataRecords, NmreDataSignal1D, NmreDataSignal2D,
    NmreDataSpectrum, NmreDataSpectrumKind, NmreDataTag, NmreDataVersion, PREDICTION_JSON_FORMAT,
    PREDICTION_JSON_VERSION, PROCESSING_RECIPE_1D_FORMAT, PROCESSING_RECIPE_2D_FORMAT,
    PROCESSING_RECIPE_JSON_VERSION, SIMULATION_JSON_VERSION, SPECTRUM_1D_JSON_FORMAT,
    SPECTRUM_2D_JSON_FORMAT, SPECTRUM_JSON_VERSION, SPIN_HALF_SYSTEM_JSON_FORMAT,
    Spectrum1DPathFormat, Spectrum1DTextWriter, Spectrum1DWriteFormat, Spectrum1DWritePathFormat,
    Spectrum2DPathFormat, Spectrum2DTextWriter, Spectrum2DWriteFormat, Spectrum2DWritePathFormat,
    SpectrumPathReader, SpectrumPathWriter, SpectrumReader, SpectrumTextFormat, SpectrumWriter,
    detect_spectrum_text_format, detect_spectrum1d_path_format,
    detect_spectrum1d_write_path_format, detect_spectrum2d_path_format,
    detect_spectrum2d_write_path_format, nmredata_1d_signals_to_assignment_set,
    nmredata_2d_signal_zone_id, nmredata_2d_signals_to_assignment_set,
    nmredata_assignments_to_assignment_set, nmredata_couplings_to_j_coupling_graph,
    nmredata_to_analysis, parse_nmredata_version, parse_nmrml_version, parse_spectrum_text_format,
    parse_spectrum1d_path_format, parse_spectrum1d_write_format,
    parse_spectrum1d_write_path_format, parse_spectrum2d_path_format,
    parse_spectrum2d_write_format, parse_spectrum2d_write_path_format, read_agilent_fid_1d_dir,
    read_agilent_fid_2d_dir, read_agilent_processed_1d_dir, read_agilent_processed_2d_dir,
    read_analysis1d_json, read_analysis2d_json, read_assignment_set_json, read_bruker_fid_1d_dir,
    read_bruker_processed_1d_dir, read_bruker_processed_2d_dir, read_bruker_ser_2d_dir,
    read_exact_decomposition_1d_json, read_exact_decomposition_2d_json,
    read_exact_spectrum_2d_options_json, read_exact_spectrum_options_json,
    read_exact_spin_options_json, read_exact_transitions_csv, read_exact_transitions_json,
    read_j_coupling_graph_json, read_jcamp_dx_1d, read_jeol_jdf_1d_bytes, read_jeol_jdf_1d_file,
    read_jeol_jdf_2d_bytes, read_jeol_jdf_2d_file, read_nmredata_bytes, read_nmredata_file,
    read_nmredata_record_json, read_nmredata_records_bytes, read_nmredata_records_file,
    read_nmredata_records_json, read_nmredata_records_str, read_nmredata_str, read_nmrml_1d_bytes,
    read_nmrml_1d_file, read_nmrml_1d_str, read_nmrml_2d_bytes, read_nmrml_2d_file,
    read_nmrml_2d_str, read_nmrml_document_info_bytes, read_nmrml_document_info_file,
    read_nmrml_document_info_str, read_prediction_csv, read_prediction_json,
    read_processing_recipe_1d_json, read_processing_recipe_2d_json, read_spectrum1d_csv,
    read_spectrum1d_json, read_spectrum1d_path, read_spectrum1d_text, read_spectrum2d_csv,
    read_spectrum2d_json, read_spectrum2d_path, read_spectrum2d_text, read_spin_half_system_json,
    write_analysis1d_csv, write_analysis1d_json, write_analysis2d_csv, write_analysis2d_json,
    write_assignment_set_json, write_exact_decomposition_1d_json,
    write_exact_decomposition_2d_json, write_exact_spectrum_2d_options_json,
    write_exact_spectrum_options_json, write_exact_spin_options_json, write_exact_transitions_csv,
    write_exact_transitions_json, write_j_coupling_graph_json, write_jcamp_dx_1d,
    write_nmredata_file, write_nmredata_record, write_nmredata_record_json, write_nmredata_records,
    write_nmredata_records_file, write_nmredata_records_json, write_nmrml_1d, write_nmrml_1d_file,
    write_nmrml_2d, write_nmrml_2d_file, write_prediction_csv, write_prediction_json,
    write_processing_recipe_1d_json, write_processing_recipe_2d_json, write_spectrum1d_csv,
    write_spectrum1d_json, write_spectrum1d_path, write_spectrum1d_text, write_spectrum2d_csv,
    write_spectrum2d_json, write_spectrum2d_path, write_spectrum2d_text,
    write_spin_half_system_json,
};
pub use prediction::{
    BondCorrelationRule, ElementShiftPredictor, ElementShiftRule, Experiment,
    PredictedCorrelation2D, PredictedSignal1D, PredictionLineShape, PredictionProvenance,
    PredictionSet, PredictionSpectrum1DResultWorkflow, PredictionSpectrum1DWorkflow,
    PredictionSpectrum2DOptions, PredictionSpectrum2DResultWorkflow, PredictionSpectrum2DWorkflow,
    PredictionSpectrumOptions, Predictor, RenderPrediction1D, RenderPrediction1DResult,
    RenderPrediction2D, RenderPrediction2DResult, StaticPrediction, predict_formula_with_rules,
    predict_molecule_with_rules, render_prediction_1d, render_prediction_2d,
};
pub use processing::{
    Abs1D, Abs2D, AutoPhase2DOptions, AutoPhase2DResult, AutoPhaseCorrection,
    AutoPhaseCorrection2D, AutoPhaseOptions, AutoPhaseResult, BaselineFit, BaselineMethod,
    BaselineReport, ContourPoint, ContourSegment, ContourSet, Crop1D, Crop2D,
    ExponentialApodization, ExponentialApodization2D, Fft1D, Fft2D, FftDirection,
    GaussianApodization, GaussianApodization2D, Magnitude, Normalize2DMaxAbs, Normalize2DVolume,
    NormalizeArea, NormalizeMaxAbs, OffsetIntensity, PhaseCorrection, PhaseCorrection2D,
    ProcessSpectrum1D, ProcessSpectrum2D, ProcessingOperation1D, ProcessingOperation2D,
    ProcessingRecipe1D, ProcessingRecipe2D, ProcessingStep, ProjectionMode, Resample1D, Resample2D,
    Scale2D, ScaleIntensity, ShiftAxis, SineBellApodization, SineBellApodization2D,
    Spectrum1DPipeline, Spectrum2DPipeline, SubtractBaseline, ZeroFill, ZeroFill2D, abs_1d, abs_2d,
    apply_processing_recipe_1d, apply_processing_recipe_1d_until, apply_processing_recipe_2d,
    apply_processing_recipe_2d_until, auto_phase_correct, auto_phase_correct_2d, contour_segments,
    crop_1d, crop_2d, exponential_apodization, exponential_apodization_2d, extract_contours,
    fft_1d, fft_2d, fit_baseline, gaussian_apodization, gaussian_apodization_2d,
    magnitude_spectrum, normalize_2d_max_abs, normalize_2d_volume, normalize_area,
    normalize_max_abs, offset_intensity, phase_correct, phase_correct_2d, project_x, project_y,
    resample_1d, resample_2d, scale_2d, scale_intensity, shift_axis, sine_bell_apodization,
    sine_bell_apodization_2d, slice_x_at_y, slice_x_at_y_index, slice_y_at_x, slice_y_at_x_index,
    spectrum_area, spectrum_volume_2d, subtract_baseline, zero_fill, zero_fill_2d,
};
pub use simulation::{
    ExactSpectrum2DOptions, ExactSpectrumDecomposition1D, ExactSpectrumDecomposition2D,
    ExactSpectrumOptions, ExactSpinHalfResultWorkflow, ExactSpinHalfSpectrum1DResultWorkflow,
    ExactSpinHalfSpectrum1DWorkflow, ExactSpinHalfSpectrum2DResultWorkflow,
    ExactSpinHalfSpectrum2DWorkflow, ExactSpinHalfWorkflow, ExactSpinOptions, ExactSpinPair,
    ExactTransition, ExactTransitionContribution1D, ExactTransitionContribution2D, LineShape,
    MAX_EXACT_SPINS, ScalarCoupling, SimulateExactSpinHalf, SimulateExactSpinHalfResult, Simulator,
    SpinHalf, SpinHalfSystem, decompose_exact_spin_half_1d, decompose_exact_spin_half_2d,
    exact_spin_half_transitions, simulate_exact_spin_half_1d, simulate_exact_spin_half_2d,
    validate_exact_spectrum_2d_options, validate_exact_spectrum_options,
    validate_exact_spin_half_inputs, validate_exact_spin_half_spectrum_2d_inputs,
    validate_exact_spin_half_spectrum_inputs, validate_exact_spin_options,
    validate_spin_half_system,
};
pub use workflow::{AnalyzeProcessedSpectrum1D, AnalyzeProcessedSpectrum2D};

/// Common imports for routine `RSpin` library workflows.
///
/// This prelude intentionally favors stable data types, IO helpers, analysis
/// primitives, processing pipeline traits, prediction types, and exact
/// simulation APIs.
pub mod prelude {
    pub use crate::{
        ANALYSIS_1D_JSON_FORMAT, ANALYSIS_2D_JSON_FORMAT, ANALYSIS_JSON_VERSION,
        ASSIGNMENT_JSON_VERSION, ASSIGNMENT_SET_JSON_FORMAT, Abs1D, Abs2D, AgilentFid1D,
        AgilentFid2D, AgilentProcessed1D, AgilentProcessed2D, AlignmentWindow,
        AnalyzeProcessedSpectrum1D, AnalyzeProcessedSpectrum2D, AnalyzeSpectrum1D,
        AnalyzeSpectrum1DResult, AnalyzeSpectrum2D, AnalyzeSpectrum2DResult, AnnotationTarget,
        AssignedAtom, Assignment, AssignmentSet, AssignmentTarget, Atom, AutoPhaseOptions,
        AutoSpectrum1DPath, AutoSpectrum1DPathWriter, AutoSpectrum1DText, AutoSpectrum2DPath,
        AutoSpectrum2DPathWriter, AutoSpectrum2DText, Axis, BaselineMethod, BilinearIntegrator2D,
        Bond, BondCorrelationRule, BondOrder, BrukerFid1D, BrukerProcessed1D, BrukerProcessed2D,
        BrukerSer2D, BucketMatrix1D, BucketMatrix2D, BucketOptions1D, BucketOptions2D,
        ClusterMerge, ConsensusPeak1D, ConsensusPeakMember1D, ConsensusPeakOptions,
        ConsensusRange1D, ConsensusRangeMember1D, ConsensusRangeOptions, ConsensusZone2D,
        ConsensusZoneMember2D, ConsensusZoneOptions, Crop1D, Crop2D, CsvAnalysis1D, CsvAnalysis2D,
        CsvExactTransitions, CsvPrediction, CsvSpectrum1D, CsvSpectrum2D, DetectedMultiplet,
        DetectedRange, DetectedZone, EXACT_DECOMPOSITION_1D_JSON_FORMAT,
        EXACT_DECOMPOSITION_2D_JSON_FORMAT, EXACT_SPECTRUM_1D_OPTIONS_JSON_FORMAT,
        EXACT_SPECTRUM_2D_OPTIONS_JSON_FORMAT, EXACT_SPIN_OPTIONS_JSON_FORMAT,
        EXACT_TRANSITIONS_JSON_FORMAT, ElementShiftPredictor, ElementShiftRule,
        ExactSpectrum2DOptions, ExactSpectrumOptions, ExactSpinHalfResultWorkflow,
        ExactSpinHalfSpectrum1DResultWorkflow, ExactSpinHalfSpectrum1DWorkflow,
        ExactSpinHalfSpectrum2DResultWorkflow, ExactSpinHalfSpectrum2DWorkflow,
        ExactSpinHalfWorkflow, ExactSpinOptions, ExactSpinPair, ExactTransition, Experiment,
        FftDirection, GaussianApodization, GaussianApodization2D, Integral, Integral2D,
        IntegralRegion, IntegralRegion2D, J_COUPLING_GRAPH_JSON_FORMAT, JCoupling, JCouplingGraph,
        JeolJdf1D, JeolJdf2D, JsonAnalysis1D, JsonAnalysis2D, JsonAssignmentSet,
        JsonExactDecomposition1D, JsonExactDecomposition2D, JsonExactSpectrum2DOptions,
        JsonExactSpectrumOptions, JsonExactSpinOptions, JsonExactTransitions, JsonJCouplingGraph,
        JsonNmreDataRecord, JsonNmreDataRecords, JsonPrediction, JsonProcessingRecipe1D,
        JsonProcessingRecipe2D, JsonSpinHalfSystem, LineShape, MatrixClusterCut,
        MatrixClusterMetric, MatrixClusterResult, MatrixClusteringOptions,
        MatrixGeneration2DOptions, MatrixGenerationOptions, MatrixLinkage, MatrixPairwiseMetric,
        MatrixPairwiseOptions, MatrixPairwiseResult, MatrixPcaOptions, MatrixPcaResult,
        MatrixScaling, Metadata, Molecule, MultipletDetectionOptions, MultipletKind,
        NMREDATA_JSON_VERSION, NMREDATA_RECORD_JSON_FORMAT, NMREDATA_RECORDS_JSON_FORMAT,
        NMRML_SCHEMA_DIRECTORY, NMRML_SCHEMA_REPOSITORY, NmrMl1D, NmrMl2D, NmrMlDocumentInfo,
        NmrMlSchemaLocation, NmrMlVersion, NmreData, NmreDataAnalysis, NmreDataAssignment,
        NmreDataCoupling, NmreDataRecord, NmreDataRecords, NmreDataSignal1D, NmreDataSignal2D,
        NmreDataSpectrum, NmreDataSpectrumKind, NmreDataTag, NmreDataVersion, Normalize2DMaxAbs,
        Normalize2DVolume, NormalizeArea, NormalizeMaxAbs, Nucleus, OptimizedPeak,
        PREDICTION_JSON_FORMAT, PREDICTION_JSON_VERSION, PROCESSING_RECIPE_1D_FORMAT,
        PROCESSING_RECIPE_2D_FORMAT, PROCESSING_RECIPE_JSON_VERSION, Peak, PeakAlignedMatrix1D,
        PeakAlignmentOptions, PeakOptimizationOptions, PeakOptimizer, PeakPickOptions,
        PeakPolarity, PredictionLineShape, PredictionSet, PredictionSpectrum1DResultWorkflow,
        PredictionSpectrum1DWorkflow, PredictionSpectrum2DOptions,
        PredictionSpectrum2DResultWorkflow, PredictionSpectrum2DWorkflow,
        PredictionSpectrumOptions, ProcessSpectrum1D, ProcessSpectrum2D, ProcessingOperation1D,
        ProcessingOperation2D, ProcessingRecipe1D, ProcessingRecipe2D, ProjectionMode,
        QuadraticPeakOptimizer, RSpinError, RangeDetectionOptions, RenderPrediction1D,
        RenderPrediction1DResult, RenderPrediction2D, RenderPrediction2DResult, Resample1D,
        Resample2D, Result, SIMULATION_JSON_VERSION, SPECTRUM_1D_JSON_FORMAT,
        SPECTRUM_2D_JSON_FORMAT, SPECTRUM_JSON_VERSION, SPIN_HALF_SYSTEM_JSON_FORMAT,
        ScalarCoupling, SignalSummary1D, SignalSummary2D, SignalSummary2DOptions,
        SignalSummaryOptions, SimulateExactSpinHalf, SimulateExactSpinHalfResult,
        SineBellApodization, SineBellApodization2D, SpectralBucket1D, SpectralBucket2D, Spectrum1D,
        Spectrum1DPathFormat, Spectrum1DTextWriter, Spectrum1DWriteFormat,
        Spectrum1DWritePathFormat, Spectrum2D, Spectrum2DAlignmentShift, Spectrum2DPathFormat,
        Spectrum2DTextWriter, Spectrum2DWriteFormat, Spectrum2DWritePathFormat, SpectrumAnalysis1D,
        SpectrumAnalysis1DOptions, SpectrumAnalysis1DResultWorkflow, SpectrumAnalysis1DWorkflow,
        SpectrumAnalysis2D, SpectrumAnalysis2DOptions, SpectrumAnalysis2DResultWorkflow,
        SpectrumAnalysis2DWorkflow, SpectrumAnnotation, SpectrumMatrix1D, SpectrumMatrix2D,
        SpectrumPathReader, SpectrumPathWriter, SpectrumReader, SpectrumTextFormat, SpectrumWriter,
        SpinHalf, SpinHalfSystem, TrapezoidalIntegrator, Unit, ZoneAlignedMatrix2D,
        ZoneAlignmentOptions, ZoneAlignmentResult2D, ZoneConnectivity, ZoneDetectionOptions,
        abs_1d, abs_2d, align_spectra_by_peak, align_spectra_by_peak_to_matrix,
        align_spectra_by_zone, align_spectra_by_zone_to_matrix, analyze_assigned_spectrum_1d,
        analyze_assigned_spectrum_2d, analyze_spectrum_1d, analyze_spectrum_2d,
        apply_processing_recipe_1d, apply_processing_recipe_1d_until, apply_processing_recipe_2d,
        apply_processing_recipe_2d_until, atoms_from_formula, auto_phase_correct,
        auto_phase_correct_2d, bucket_spectra_1d, bucket_spectra_2d, bucket_spectrum_1d,
        bucket_spectrum_2d, cluster_bucket_matrix_1d, cluster_bucket_matrix_2d, cluster_matrix,
        cluster_spectrum_matrix_1d, cluster_spectrum_matrix_2d, crop_1d, crop_2d,
        decompose_exact_spin_half_1d, decompose_exact_spin_half_2d, detect_consensus_peaks_1d,
        detect_consensus_ranges_1d, detect_consensus_zones_2d, detect_multiplets, detect_ranges,
        detect_spectrum_text_format, detect_spectrum1d_path_format,
        detect_spectrum1d_write_path_format, detect_spectrum2d_path_format,
        detect_spectrum2d_write_path_format, detect_zones, exact_spin_half_transitions,
        extract_contours, gaussian_apodization, gaussian_apodization_2d,
        generate_spectrum_matrix_1d, generate_spectrum_matrix_2d, integrate_ranges,
        integrate_region, integrate_region_2d, integrate_regions, integrate_regions_2d,
        integrate_zones_2d, nmredata_1d_signals_to_assignment_set, nmredata_2d_signal_zone_id,
        nmredata_2d_signals_to_assignment_set, nmredata_assignments_to_assignment_set,
        nmredata_couplings_to_j_coupling_graph, nmredata_to_analysis, normalize_2d_max_abs,
        normalize_2d_volume, normalize_area, normalize_max_abs, pairwise_bucket_matrix_1d,
        pairwise_bucket_matrix_2d, pairwise_matrix, pairwise_spectrum_matrix_1d,
        pairwise_spectrum_matrix_2d, parse_nmredata_version, parse_nmrml_version,
        parse_spectrum_text_format, parse_spectrum1d_path_format, parse_spectrum1d_write_format,
        parse_spectrum1d_write_path_format, parse_spectrum2d_path_format,
        parse_spectrum2d_write_format, parse_spectrum2d_write_path_format, pca_bucket_matrix_1d,
        pca_bucket_matrix_2d, pca_matrix, pca_spectrum_matrix_1d, pca_spectrum_matrix_2d,
        pick_peaks, predict_formula_with_rules, predict_molecule_with_rules,
        read_agilent_fid_1d_dir, read_agilent_fid_2d_dir, read_agilent_processed_1d_dir,
        read_agilent_processed_2d_dir, read_analysis1d_json, read_analysis2d_json,
        read_assignment_set_json, read_bruker_fid_1d_dir, read_bruker_processed_1d_dir,
        read_bruker_processed_2d_dir, read_bruker_ser_2d_dir, read_exact_decomposition_1d_json,
        read_exact_decomposition_2d_json, read_exact_spectrum_2d_options_json,
        read_exact_spectrum_options_json, read_exact_spin_options_json, read_exact_transitions_csv,
        read_exact_transitions_json, read_j_coupling_graph_json, read_jcamp_dx_1d,
        read_jeol_jdf_1d_bytes, read_jeol_jdf_1d_file, read_jeol_jdf_2d_bytes,
        read_jeol_jdf_2d_file, read_nmredata_bytes, read_nmredata_file, read_nmredata_record_json,
        read_nmredata_records_bytes, read_nmredata_records_file, read_nmredata_records_json,
        read_nmredata_records_str, read_nmredata_str, read_nmrml_1d_bytes, read_nmrml_1d_file,
        read_nmrml_1d_str, read_nmrml_2d_bytes, read_nmrml_2d_file, read_nmrml_2d_str,
        read_nmrml_document_info_bytes, read_nmrml_document_info_file,
        read_nmrml_document_info_str, read_prediction_csv, read_prediction_json,
        read_processing_recipe_1d_json, read_processing_recipe_2d_json, read_spectrum1d_csv,
        read_spectrum1d_json, read_spectrum1d_path, read_spectrum1d_text, read_spectrum2d_csv,
        read_spectrum2d_json, read_spectrum2d_path, read_spectrum2d_text,
        read_spin_half_system_json, render_prediction_1d, render_prediction_2d, resample_1d,
        resample_2d, scale_intensity, simulate_exact_spin_half_1d, simulate_exact_spin_half_2d,
        sine_bell_apodization, sine_bell_apodization_2d, slice_x_at_y, slice_y_at_x, spectrum_area,
        spectrum_volume_2d, subtract_baseline, summarize_signals_2d,
        validate_exact_spectrum_2d_options, validate_exact_spectrum_options,
        validate_exact_spin_half_inputs, validate_exact_spin_half_spectrum_2d_inputs,
        validate_exact_spin_half_spectrum_inputs, validate_exact_spin_options,
        validate_spin_half_system, write_analysis1d_csv, write_analysis1d_json,
        write_analysis2d_csv, write_analysis2d_json, write_assignment_set_json,
        write_exact_decomposition_1d_json, write_exact_decomposition_2d_json,
        write_exact_spectrum_2d_options_json, write_exact_spectrum_options_json,
        write_exact_spin_options_json, write_exact_transitions_csv, write_exact_transitions_json,
        write_j_coupling_graph_json, write_jcamp_dx_1d, write_nmredata_file, write_nmredata_record,
        write_nmredata_record_json, write_nmredata_records, write_nmredata_records_file,
        write_nmredata_records_json, write_nmrml_1d, write_nmrml_1d_file, write_nmrml_2d,
        write_nmrml_2d_file, write_prediction_csv, write_prediction_json,
        write_processing_recipe_1d_json, write_processing_recipe_2d_json, write_spectrum1d_csv,
        write_spectrum1d_json, write_spectrum1d_path, write_spectrum1d_text, write_spectrum2d_csv,
        write_spectrum2d_json, write_spectrum2d_path, write_spectrum2d_text,
        write_spin_half_system_json,
    };
}

#[cfg(test)]
mod tests;
