//! Public facade for the `RSpin` library workspace.

pub use rspin_analysis as analysis;
pub use rspin_core as core;
pub use rspin_io as io;
pub use rspin_prediction as prediction;
pub use rspin_processing as processing;
pub use rspin_simulation as simulation;

pub use analysis::{
    AlignmentWindow, AnalyzeSpectrum1D, AnalyzeSpectrum1DResult, AnalyzeSpectrum2D,
    AnalyzeSpectrum2DResult, AssignedAtom, Assignment, AssignmentSet, AssignmentTarget,
    BilinearIntegrator2D, BucketMatrix1D, BucketMatrix2D, BucketOptions1D, BucketOptions2D,
    ClusterMerge, ConsensusPeak1D, ConsensusPeakMember1D, ConsensusPeakOptions, ConsensusRange1D,
    ConsensusRangeMember1D, ConsensusRangeOptions, ConsensusZone2D, ConsensusZoneMember2D,
    ConsensusZoneOptions, CouplingNode, DetectedMultiplet, DetectedRange, DetectedZone,
    GapMultipletDetector, Integral, Integral2D, IntegralRegion, IntegralRegion2D, Integrator,
    Integrator2D, JCoupling, JCouplingGraph, LocalExtremaPeakPicker, MatrixClusterCut,
    MatrixClusterMetric, MatrixClusterResult, MatrixClusteringOptions, MatrixGeneration2DOptions,
    MatrixGenerationOptions, MatrixLinkage, MatrixPairwiseMetric, MatrixPairwiseOptions,
    MatrixPairwiseResult, MatrixPcaOptions, MatrixPcaResult, MatrixScaling,
    MultipletDetectionOptions, MultipletDetector, MultipletKind, OptimizedPeak, Peak,
    PeakAlignedMatrix1D, PeakAlignmentOptions, PeakAlignmentResult1D, PeakOptimizationOptions,
    PeakOptimizer, PeakPickOptions, PeakPicker, PeakPolarity, QuadraticPeakOptimizer,
    RangeDetectionOptions, RangeDetector, SignalSummary1D, SignalSummary2D, SignalSummary2DOptions,
    SignalSummaryOptions, SpectralBucket1D, SpectralBucket2D, Spectrum2DAlignmentShift,
    SpectrumAlignmentShift, SpectrumAnalysis1D, SpectrumAnalysis1DOptions,
    SpectrumAnalysis1DResultWorkflow, SpectrumAnalysis1DWorkflow, SpectrumAnalysis2D,
    SpectrumAnalysis2DOptions, SpectrumAnalysis2DResultWorkflow, SpectrumAnalysis2DWorkflow,
    SpectrumMatrix1D, SpectrumMatrix2D, ThresholdRangeDetector, ThresholdZoneDetector,
    TrapezoidalIntegrator, ZoneAlignedMatrix2D, ZoneAlignmentOptions, ZoneAlignmentResult2D,
    ZoneConnectivity, ZoneDetectionOptions, ZoneDetector, align_spectra_by_peak,
    align_spectra_by_peak_to_matrix, align_spectra_by_zone, align_spectra_by_zone_to_matrix,
    analyze_assigned_spectrum_1d, analyze_assigned_spectrum_2d, analyze_spectrum_1d,
    analyze_spectrum_2d, bucket_spectra_1d, bucket_spectra_2d, bucket_spectrum_1d,
    bucket_spectrum_2d, cluster_bucket_matrix_1d, cluster_bucket_matrix_2d, cluster_matrix,
    cluster_spectrum_matrix_1d, cluster_spectrum_matrix_2d, detect_consensus_peaks_1d,
    detect_consensus_ranges_1d, detect_consensus_zones_2d, detect_multiplets, detect_ranges,
    detect_zones, deterministic_assignment_id, deterministic_j_coupling_id,
    generate_spectrum_matrix_1d, generate_spectrum_matrix_2d, integrate_region,
    integrate_region_2d, optimize_peaks_quadratic, pairwise_bucket_matrix_1d,
    pairwise_bucket_matrix_2d, pairwise_matrix, pairwise_spectrum_matrix_1d,
    pairwise_spectrum_matrix_2d, pca_bucket_matrix_1d, pca_bucket_matrix_2d, pca_matrix,
    pca_spectrum_matrix_1d, pca_spectrum_matrix_2d, pick_peaks, summarize_signals_1d,
    summarize_signals_2d,
};
pub use core::{
    AnnotationTarget, Atom, Axis, Bond, BondOrder, Metadata, Molecule, Nucleus, ProcessingRecord,
    RSpinError, Result, Spectrum1D, Spectrum2D, SpectrumAnnotation, Unit,
};
pub use io::{
    AgilentFid1D, AgilentFid2D, AutoSpectrum1DPath, AutoSpectrum1DText, AutoSpectrum2DPath,
    AutoSpectrum2DText, BrukerFid1D, BrukerProcessed1D, BrukerProcessed2D, BrukerSer2D,
    CsvAnalysis1D, CsvAnalysis2D, CsvSpectrum1D, CsvSpectrum2D, JcampDx, JeolJdf1D, JeolJdf2D,
    JsonAnalysis1D, JsonAnalysis2D, JsonProcessingRecipe1D, JsonProcessingRecipe2D, JsonSpectrum1D,
    JsonSpectrum2D, NmrMl1D, NmrMl2D, Spectrum1DPathFormat, Spectrum2DPathFormat,
    SpectrumPathReader, SpectrumReader, SpectrumTextFormat, SpectrumWriter,
    detect_spectrum_text_format, detect_spectrum1d_path_format, detect_spectrum2d_path_format,
    read_agilent_fid_1d_dir, read_agilent_fid_2d_dir, read_analysis1d_json, read_analysis2d_json,
    read_bruker_fid_1d_dir, read_bruker_processed_1d_dir, read_bruker_processed_2d_dir,
    read_bruker_ser_2d_dir, read_jcamp_dx_1d, read_jeol_jdf_1d_bytes, read_jeol_jdf_1d_file,
    read_jeol_jdf_2d_bytes, read_jeol_jdf_2d_file, read_nmrml_1d_bytes, read_nmrml_1d_file,
    read_nmrml_1d_str, read_nmrml_2d_bytes, read_nmrml_2d_file, read_nmrml_2d_str,
    read_processing_recipe_1d_json, read_processing_recipe_2d_json, read_spectrum1d_csv,
    read_spectrum1d_json, read_spectrum1d_path, read_spectrum1d_text, read_spectrum2d_csv,
    read_spectrum2d_json, read_spectrum2d_path, read_spectrum2d_text, write_analysis1d_csv,
    write_analysis1d_json, write_analysis2d_csv, write_analysis2d_json, write_jcamp_dx_1d,
    write_processing_recipe_1d_json, write_processing_recipe_2d_json, write_spectrum1d_csv,
    write_spectrum1d_json, write_spectrum2d_csv, write_spectrum2d_json,
};
pub use prediction::{
    BondCorrelationRule, ElementShiftPredictor, ElementShiftRule, Experiment,
    PredictedCorrelation2D, PredictedSignal1D, PredictionLineShape, PredictionProvenance,
    PredictionSet, PredictionSpectrum2DOptions, PredictionSpectrumOptions, Predictor,
    StaticPrediction, predict_molecule_with_rules, render_prediction_1d, render_prediction_2d,
};
pub use processing::{
    Abs1D, Abs2D, AutoPhase2DOptions, AutoPhase2DResult, AutoPhaseCorrection,
    AutoPhaseCorrection2D, AutoPhaseOptions, AutoPhaseResult, BaselineFit, BaselineMethod,
    BaselineReport, ContourPoint, ContourSegment, ContourSet, Crop1D, Crop2D,
    ExponentialApodization, ExponentialApodization2D, Fft1D, Fft2D, FftDirection, Magnitude,
    Normalize2DMaxAbs, NormalizeMaxAbs, OffsetIntensity, PhaseCorrection, PhaseCorrection2D,
    ProcessSpectrum1D, ProcessSpectrum2D, ProcessingOperation1D, ProcessingOperation2D,
    ProcessingRecipe1D, ProcessingRecipe2D, ProcessingStep, ProjectionMode, Resample1D, Resample2D,
    Scale2D, ScaleIntensity, ShiftAxis, Spectrum1DPipeline, Spectrum2DPipeline, SubtractBaseline,
    ZeroFill, ZeroFill2D, abs_1d, abs_2d, apply_processing_recipe_1d,
    apply_processing_recipe_1d_until, apply_processing_recipe_2d, apply_processing_recipe_2d_until,
    auto_phase_correct, auto_phase_correct_2d, contour_segments, crop_1d, crop_2d,
    exponential_apodization, exponential_apodization_2d, extract_contours, fft_1d, fft_2d,
    fit_baseline, magnitude_spectrum, normalize_2d_max_abs, normalize_max_abs, offset_intensity,
    phase_correct, phase_correct_2d, project_x, project_y, resample_1d, resample_2d, scale_2d,
    scale_intensity, shift_axis, slice_x_at_y, slice_x_at_y_index, slice_y_at_x,
    slice_y_at_x_index, subtract_baseline, zero_fill, zero_fill_2d,
};
pub use simulation::{
    ExactSpectrum2DOptions, ExactSpectrumDecomposition1D, ExactSpectrumDecomposition2D,
    ExactSpectrumOptions, ExactSpinOptions, ExactSpinPair, ExactTransition,
    ExactTransitionContribution1D, ExactTransitionContribution2D, LineShape, MAX_EXACT_SPINS,
    ScalarCoupling, Simulator, SpinHalf, SpinHalfSystem, decompose_exact_spin_half_1d,
    decompose_exact_spin_half_2d, exact_spin_half_transitions, simulate_exact_spin_half_1d,
    simulate_exact_spin_half_2d,
};

/// Common imports for routine `RSpin` library workflows.
///
/// This prelude intentionally favors stable data types, IO helpers, analysis
/// primitives, processing pipeline traits, prediction types, and exact
/// simulation APIs.
pub mod prelude {
    pub use crate::{
        Abs1D, Abs2D, AgilentFid1D, AgilentFid2D, AlignmentWindow, AnalyzeSpectrum1D,
        AnalyzeSpectrum1DResult, AnalyzeSpectrum2D, AnalyzeSpectrum2DResult, AnnotationTarget,
        AssignedAtom, Assignment, AssignmentSet, AssignmentTarget, Atom, AutoPhaseOptions,
        AutoSpectrum1DPath, AutoSpectrum1DText, AutoSpectrum2DPath, AutoSpectrum2DText, Axis,
        BaselineMethod, BilinearIntegrator2D, Bond, BondCorrelationRule, BondOrder, BrukerFid1D,
        BrukerProcessed1D, BrukerProcessed2D, BrukerSer2D, BucketMatrix1D, BucketMatrix2D,
        BucketOptions1D, BucketOptions2D, ClusterMerge, ConsensusPeak1D, ConsensusPeakMember1D,
        ConsensusPeakOptions, ConsensusRange1D, ConsensusRangeMember1D, ConsensusRangeOptions,
        ConsensusZone2D, ConsensusZoneMember2D, ConsensusZoneOptions, Crop1D, Crop2D,
        CsvAnalysis1D, CsvAnalysis2D, CsvSpectrum1D, CsvSpectrum2D, DetectedMultiplet,
        DetectedRange, DetectedZone, ElementShiftPredictor, ElementShiftRule,
        ExactSpectrum2DOptions, ExactSpectrumOptions, ExactSpinOptions, ExactSpinPair,
        ExactTransition, Experiment, FftDirection, Integral, Integral2D, IntegralRegion,
        IntegralRegion2D, JCoupling, JCouplingGraph, JeolJdf1D, JeolJdf2D, JsonAnalysis1D,
        JsonAnalysis2D, JsonProcessingRecipe1D, JsonProcessingRecipe2D, LineShape,
        MatrixClusterCut, MatrixClusterMetric, MatrixClusterResult, MatrixClusteringOptions,
        MatrixGeneration2DOptions, MatrixGenerationOptions, MatrixLinkage, MatrixPairwiseMetric,
        MatrixPairwiseOptions, MatrixPairwiseResult, MatrixPcaOptions, MatrixPcaResult,
        MatrixScaling, Metadata, Molecule, MultipletDetectionOptions, MultipletKind, NmrMl1D,
        NmrMl2D, Nucleus, Peak, PeakAlignedMatrix1D, PeakAlignmentOptions, PeakPickOptions,
        PeakPolarity, PredictionLineShape, PredictionSet, PredictionSpectrum2DOptions,
        PredictionSpectrumOptions, ProcessSpectrum1D, ProcessSpectrum2D, ProcessingOperation1D,
        ProcessingOperation2D, ProcessingRecipe1D, ProcessingRecipe2D, ProjectionMode, RSpinError,
        RangeDetectionOptions, Resample1D, Resample2D, Result, ScalarCoupling, SignalSummary1D,
        SignalSummary2D, SignalSummary2DOptions, SignalSummaryOptions, SpectralBucket1D,
        SpectralBucket2D, Spectrum1D, Spectrum1DPathFormat, Spectrum2D, Spectrum2DAlignmentShift,
        Spectrum2DPathFormat, SpectrumAnalysis1D, SpectrumAnalysis1DOptions,
        SpectrumAnalysis1DResultWorkflow, SpectrumAnalysis1DWorkflow, SpectrumAnalysis2D,
        SpectrumAnalysis2DOptions, SpectrumAnalysis2DResultWorkflow, SpectrumAnalysis2DWorkflow,
        SpectrumAnnotation, SpectrumMatrix1D, SpectrumMatrix2D, SpectrumPathReader, SpectrumReader,
        SpectrumTextFormat, SpectrumWriter, SpinHalf, SpinHalfSystem, TrapezoidalIntegrator, Unit,
        ZoneAlignedMatrix2D, ZoneAlignmentOptions, ZoneAlignmentResult2D, ZoneConnectivity,
        ZoneDetectionOptions, abs_1d, abs_2d, align_spectra_by_peak,
        align_spectra_by_peak_to_matrix, align_spectra_by_zone, align_spectra_by_zone_to_matrix,
        analyze_assigned_spectrum_1d, analyze_assigned_spectrum_2d, analyze_spectrum_1d,
        analyze_spectrum_2d, apply_processing_recipe_1d, apply_processing_recipe_1d_until,
        apply_processing_recipe_2d, apply_processing_recipe_2d_until, auto_phase_correct,
        auto_phase_correct_2d, bucket_spectra_1d, bucket_spectra_2d, bucket_spectrum_1d,
        bucket_spectrum_2d, cluster_bucket_matrix_1d, cluster_bucket_matrix_2d, cluster_matrix,
        cluster_spectrum_matrix_1d, cluster_spectrum_matrix_2d, crop_1d, crop_2d,
        decompose_exact_spin_half_1d, decompose_exact_spin_half_2d, detect_consensus_peaks_1d,
        detect_consensus_ranges_1d, detect_consensus_zones_2d, detect_multiplets, detect_ranges,
        detect_spectrum_text_format, detect_spectrum1d_path_format, detect_spectrum2d_path_format,
        detect_zones, exact_spin_half_transitions, extract_contours, generate_spectrum_matrix_1d,
        generate_spectrum_matrix_2d, integrate_region, integrate_region_2d, normalize_max_abs,
        pairwise_bucket_matrix_1d, pairwise_bucket_matrix_2d, pairwise_matrix,
        pairwise_spectrum_matrix_1d, pairwise_spectrum_matrix_2d, pca_bucket_matrix_1d,
        pca_bucket_matrix_2d, pca_matrix, pca_spectrum_matrix_1d, pca_spectrum_matrix_2d,
        pick_peaks, predict_molecule_with_rules, read_agilent_fid_1d_dir, read_agilent_fid_2d_dir,
        read_analysis1d_json, read_analysis2d_json, read_bruker_fid_1d_dir,
        read_bruker_processed_1d_dir, read_bruker_processed_2d_dir, read_bruker_ser_2d_dir,
        read_jcamp_dx_1d, read_jeol_jdf_1d_bytes, read_jeol_jdf_1d_file, read_jeol_jdf_2d_bytes,
        read_jeol_jdf_2d_file, read_nmrml_1d_bytes, read_nmrml_1d_file, read_nmrml_1d_str,
        read_nmrml_2d_bytes, read_nmrml_2d_file, read_nmrml_2d_str, read_processing_recipe_1d_json,
        read_processing_recipe_2d_json, read_spectrum1d_csv, read_spectrum1d_json,
        read_spectrum1d_path, read_spectrum1d_text, read_spectrum2d_csv, read_spectrum2d_json,
        read_spectrum2d_path, read_spectrum2d_text, render_prediction_1d, render_prediction_2d,
        resample_1d, resample_2d, scale_intensity, simulate_exact_spin_half_1d,
        simulate_exact_spin_half_2d, slice_x_at_y, slice_y_at_x, subtract_baseline,
        summarize_signals_2d, write_analysis1d_csv, write_analysis1d_json, write_analysis2d_csv,
        write_analysis2d_json, write_jcamp_dx_1d, write_processing_recipe_1d_json,
        write_processing_recipe_2d_json, write_spectrum1d_csv, write_spectrum1d_json,
        write_spectrum2d_csv, write_spectrum2d_json,
    };
}

#[cfg(test)]
mod tests;
